# Cas test: "bump" | "diamond" | "naca0012"
case = "diamond"

# Physique
rho_inf = 1.0
p_inf = 1.0
Mach = 1.2
gamma = 1.4
aoa = 2.0

# Solveur
# time_scheme: "EE" | "RK2" | "RK4" | "SRK2" | "SSP_RK2"
time_scheme = "SRK2"
# flux: "Rusanov" | "Tadmor" | "AUSM" | "Roe" | "HLLC"
flux = "HLLC"
# reconstruction: "constant" | "MUSCL"
reconstruction = "MUSCL"
CFL = 0.6
tf = 4.0
stationarity_threshold = 1e-6
stationarity_check_every = 10000 

# Maillage (doit correspondre au case)
mesh_path = "meshes/diamond/diamond_h0.05.npy"

[export]
# results: true/false
results = false
# figures: false | [] pour rien exporter, sinon liste de champs parmi
# "rho", "u", "v", "p", "M", "S"
figures = ["M"]
graph = false
summary = false
bundle = true
# Nombre de snapshots exportés si on active les figures/bundle/results
n_snaps = 1
